//Ignacio Parrado - 303400
//Ezequiel Peña - 224585
package Interfaz;

import Dominio.Evaluador;
import Dominio.Sistema;
import Excepciones.CampoVacioException;
import Excepciones.CedulaFormatoException;
import Excepciones.CedulaRepetidaException;
import Excepciones.VerificoAñoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author elnac
 */
public class VentanaRegistroEvaluador extends javax.swing.JFrame {

    private Sistema modelo;

    public VentanaRegistroEvaluador(Sistema sistema) {
        this.modelo = sistema;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNombre1 = new javax.swing.JLabel();
        lblCedula = new javax.swing.JLabel();
        lblAño = new javax.swing.JLabel();
        lblDireccion1 = new javax.swing.JLabel();
        lblAltaPostulante = new javax.swing.JLabel();
        txtAño = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtCedula = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        btnCancelar = new javax.swing.JButton();
        btnSiguiente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registro Evaluador");
        setResizable(false);
        getContentPane().setLayout(null);

        lblNombre1.setText("Nombre:");
        getContentPane().add(lblNombre1);
        lblNombre1.setBounds(60, 80, 80, 20);

        lblCedula.setText("Cedula:");
        getContentPane().add(lblCedula);
        lblCedula.setBounds(60, 120, 70, 20);

        lblAño.setText("Año de ingreso:");
        getContentPane().add(lblAño);
        lblAño.setBounds(60, 200, 100, 20);

        lblDireccion1.setText("Direccion:");
        getContentPane().add(lblDireccion1);
        lblDireccion1.setBounds(60, 160, 70, 20);

        lblAltaPostulante.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblAltaPostulante.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAltaPostulante.setText("Registro Evaluador");
        getContentPane().add(lblAltaPostulante);
        lblAltaPostulante.setBounds(140, 20, 120, 16);
        getContentPane().add(txtAño);
        txtAño.setBounds(180, 200, 160, 22);
        getContentPane().add(txtNombre);
        txtNombre.setBounds(180, 80, 160, 22);
        getContentPane().add(txtCedula);
        txtCedula.setBounds(180, 120, 160, 22);
        getContentPane().add(txtDireccion);
        txtDireccion.setBounds(180, 160, 160, 22);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar);
        btnCancelar.setBounds(80, 260, 76, 23);

        btnSiguiente.setText("Aceptar");
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });
        getContentPane().add(btnSiguiente);
        btnSiguiente.setBounds(260, 260, 80, 23);

        setSize(new java.awt.Dimension(414, 351));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        String nombre = txtNombre.getText();
        String cedula = txtCedula.getText();
        String direccion = txtDireccion.getText();
        String año = txtAño.getText();
        try {
            if (this.modelo.campoNoEstaVacio(nombre, "Nombre")
                    && this.modelo.campoNoEstaVacio(cedula, "Cedula")
                    && this.modelo.verificoCedula(cedula, "Evaluador")
                    && this.modelo.campoNoEstaVacio(direccion, "Dirección")
                    && this.modelo.campoNoEstaVacio(año, "Año")
                    && this.modelo.verificoAño(año) 
                    ) {
                Evaluador ev = new Evaluador(nombre, cedula, direccion, año);
                modelo.agregarEvaluador(ev);
                this.dispose();
                JOptionPane.showMessageDialog(null, "El evaluador fue agregado con éxito", "Aviso", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (CampoVacioException e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Alerta", JOptionPane.WARNING_MESSAGE);
        } catch (CedulaRepetidaException e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Alerta", JOptionPane.WARNING_MESSAGE);
        } catch (CedulaFormatoException e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Alerta", JOptionPane.WARNING_MESSAGE);
        } catch (VerificoAñoException e) {
           JOptionPane.showMessageDialog(null, e.getMessage(), "Alerta", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnSiguienteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JLabel lblAltaPostulante;
    private javax.swing.JLabel lblAño;
    private javax.swing.JLabel lblCedula;
    private javax.swing.JLabel lblDireccion1;
    private javax.swing.JLabel lblNombre1;
    private javax.swing.JTextField txtAño;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
